# create separate namespace
apiVersion: v1
kind: Namespace
metadata:
  name: yt-notifier-namespace
---
# create config map
# for config.yaml
# and cookies.txt (optional)
apiVersion: v1
kind: ConfigMap
metadata:
  name: yt-notifier-config
  namespace: yt-notifier-namespace
data:
  config.yaml: |
    bot:
      token: XXXXXXXXXXXXXXXXXXXXX
    chat_id: -100XXXXXXXXXXXXXXXXX
    temp_chat_id: -100XXXXXXXXXXXX
    report:
      template: | 
          <h1>✅ СЕЙЧАС В ЭФИРЕ:</h1>
          <br/>
          <ol type='1'>
          {% for channel in channels %}
              <li>
                  <b><a href='{{channel.url}}'>{{channel.label}}</a></b> <br/>
                  {% if channel.concurrent_view_count is not none %}
                      <b>👀{{channel.concurrent_view_count}}</b>
                  {% endif %}
                  {% if channel.like_count is not none %}
                      <b>👍{{channel.like_count}}</b>
                  {% endif %}
                  {% if channel.duration is not none %}
                      <b>🕑{{channel.duration}}</b>
                  {% endif %}
              </li>
              <br/>
          {% endfor %}
          </ol>
          <hr/>
          <i>💬 Заходите в наш <a href='https://t.me/Discordovchat'>чат</a>.</i>
          <br/>
          <i>🤖 <a href='https://t.me/discordovo_feedback_bot'>Бот-предложка</a>, присылайте интересные ссылки на каналы/видео/картинки. </i>
      empty: | 
        <b>🤷 Интересных стримов сейчас нет.</b>
        <hr/>
        <i>💬 Заходите в наш <a href='https://t.me/Discordovchat'>чат</a>.</i>
        <br/>
        <i>🤖 <a href='https://t.me/discordovo_feedback_bot'>Бот-предложка</a>, присылайте интересные ссылки на каналы/видео/картинки. </i>

    start_scheduler: True
    interval_s: 300
  cookies.txt: |
    # Netscape HTTP Cookie File
    # This file is generated by yt-dlp.  Do not edit.
---
# create persistent volume for database
apiVersion: v1
kind: PersistentVolume
metadata:
  name: yt-notifier-pv
  namespace: yt-notifier-namespace
spec:
  capacity:
    storage: 128Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  local:
    path: /path/to/database/on/host/machine
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - my-k8s-node  # get value from kubectl get nodes
---
# create volume claim for database
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yt-notifier-pvc
  namespace: yt-notifier-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  storageClassName: local-path
---
# create deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yt-notifier
  namespace: yt-notifier-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yt-notifier
  template:
    metadata:
      labels:
        app: yt-notifier
    spec:
      containers:
      - name: yt-notifier
        image: bral1488/telegram-youtube-notifier:main
        imagePullPolicy: Always
        command: ["sh", "-c", "python -m src"]
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.yaml
          subPath: config.yaml
          readOnly: true
        - name: config-volume
          mountPath: /app/cookies.txt
          subPath: cookies.txt
          readOnly: true
        - name: db-volume
          mountPath: /db/youtube-notifier-bot.db
          subPath: youtube-notifier-bot.db
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        securityContext:
          runAsUser: 0
        env:
          - name: SQLITE_DATABASE_FILE_PATH
            value: "/db/youtube-notifier-bot.db"
      volumes:
      - name: config-volume
        configMap:
          name: yt-notifier-config
      - name: db-volume
        persistentVolumeClaim:
          claimName: yt-notifier-pvc
      tolerations:
      - key: "node.kubernetes.io/disk-pressure"
        operator: "Exists"
        effect: "NoSchedule"
