version: '2.2'

services:
  yt-notifier:
    image: bral1488/telegram-youtube-notifier:main
    container_name: telegram-youtube-notifier
    restart: always
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./messages.dump:/app/messages.dump
      - ./cookies.txt://app/cookies.txt
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: bash -c "python -m src"

